"""
OniQuant v6.0 — Phase 5.5: Bayesian Decision Engine (Orchestrator)
====================================================================
Final arbiter for all signals generated by the Alpha Stack.
Authorizes or rejects signals based on Bayesian Posterior Probability
with a hard floor of 69.5%.

Bayes' Theorem:
                    P(B|A) × P(A)
    P(A|B)  =  ─────────────────────
                       P(B)

Where:
    P(A)    = Prior: 30-day historical win rate from TimescaleDB
    P(B|A)  = Likelihood: adjusted by IOF strength, macro alignment, Hurst exponent
    P(B)    = Evidence: marginal probability (normalizing constant)
    P(A|B)  = Posterior: final decision probability

Decision Rule:
    If P(A|B) > 0.695 → AUTHORIZE (route to broker)
    If P(A|B) ≤ 0.695 → REJECT (drop silently)

Routing:
    TradFi (equities, forex, metals) → broker_tradfi.py (IBKR_TWS)
    Crypto (perpetuals, spot)        → broker_crypto.py (BYBIT_V5)

Deploy: Railway.app — imported by the signal processing pipeline.
"""

from __future__ import annotations

import asyncio
import math
import os
import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

import orjson
import redis.asyncio as aioredis
import structlog

# ---------------------------------------------------------------------------
# Logger
# ---------------------------------------------------------------------------
log: structlog.stdlib.BoundLogger = structlog.get_logger("oniquant.orchestrator")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
REDIS_URL: str = os.getenv("REDIS_URL", "redis://localhost:6379/0")
POSTERIOR_FLOOR: float = float(os.getenv("POSTERIOR_FLOOR", "0.695"))
EXEC_STREAM: str = "oniquant:active_executions"
EXEC_STREAM_MAXLEN: int = int(os.getenv("EXEC_STREAM_MAXLEN", "25000"))

# Likelihood multiplier bounds — prevent runaway posteriors
LIKELIHOOD_CAP: float = 3.0   # max combined likelihood multiplier
LIKELIHOOD_FLOOR: float = 0.3  # min combined likelihood multiplier


# ---------------------------------------------------------------------------
# 1. Enums & Data Structures
# ---------------------------------------------------------------------------

class Decision(str, Enum):
    AUTHORIZE = "AUTHORIZE"
    REJECT = "REJECT"


class RoutingTarget(str, Enum):
    IBKR_TWS = "IBKR_TWS"
    BYBIT_V5 = "BYBIT_V5"


# Asset class → routing target mapping
ROUTING_MAP: dict[str, RoutingTarget] = {
    # TradFi → IBKR
    "equity": RoutingTarget.IBKR_TWS,
    "forex": RoutingTarget.IBKR_TWS,
    "metals": RoutingTarget.IBKR_TWS,
    "futures": RoutingTarget.IBKR_TWS,
    "index": RoutingTarget.IBKR_TWS,
    # Crypto → Bybit
    "crypto": RoutingTarget.BYBIT_V5,
    "perpetual": RoutingTarget.BYBIT_V5,
    "spot_crypto": RoutingTarget.BYBIT_V5,
}


@dataclass(frozen=True, slots=True)
class SignalInput:
    """
    Inbound signal from the Alpha Stack for Bayesian evaluation.

    Attributes:
        signal_id: Unique identifier (UUID4).
        asset_symbol: Instrument symbol (e.g., "SPY", "BTCUSDT").
        asset_class: Classification for routing ("equity", "crypto", etc.).
        desk_id: Originating desk (e.g., "luxalgo_spx", "knn_btc").
        direction: 1 = LONG, -1 = SHORT.
        target_price: Model's predicted target price.
        confidence: Model's raw confidence score [0.0, 1.0].
        model_source: Which Alpha Stack model generated this ("knn", "spline", "iof").
        iof_strength: Institutional Order Flow strength [0.0, 1.0].
        hurst_exponent: Hurst exponent of the asset's price series.
        macro_context: Dict with macro indicators (dxy_trend, yield_10y_trend, etc.).
        indicator_metadata: Raw indicator state for logging/audit.
    """
    signal_id: str
    asset_symbol: str
    asset_class: str
    desk_id: str
    direction: int
    target_price: float
    confidence: float
    model_source: str
    iof_strength: float = 0.5
    hurst_exponent: float = 0.5
    macro_context: dict[str, Any] = field(default_factory=dict)
    indicator_metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class OrchestratorOutput:
    """
    Decision output from the Bayesian Orchestrator.

    This is the strictly formatted JSON object returned for every
    signal evaluation. Serialized via orjson for downstream consumers.
    """
    signal_id: str
    posterior_probability: float
    decision: str
    routing_target: str | None
    reasoning_math: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "signal_id": self.signal_id,
            "posterior_probability": round(self.posterior_probability, 6),
            "decision": self.decision,
            "routing_target": self.routing_target,
            "reasoning_math": self.reasoning_math,
        }


# ---------------------------------------------------------------------------
# 2. Prior Probability — TimescaleDB Historical Win Rate
# ---------------------------------------------------------------------------

async def fetch_prior(
    asset_symbol: str,
    desk_id: str,
    redis_pool: aioredis.Redis,
    lookback_days: int = 30,
) -> float:
    """
    Retrieve the Prior Probability P(A) from TimescaleDB.

    In production, this queries the signal_ledger continuous aggregate:

        SELECT
            COUNT(*) FILTER (WHERE outcome = 'WIN') AS wins,
            COUNT(*) AS total
        FROM signal_ledger
        WHERE asset_symbol = $1
          AND desk_id = $2
          AND ts >= NOW() - INTERVAL '30 days';

        P(A) = wins / total

    Current implementation reads from a Redis cache that the TimescaleDB
    aggregation worker populates. Falls back to a neutral 0.50 prior
    if no historical data exists (uninformative prior).

    Cache key: oniquant:prior:{asset_symbol}:{desk_id}
    """
    cache_key = f"oniquant:prior:{asset_symbol}:{desk_id}"
    cached = await redis_pool.get(cache_key)

    if cached is not None:
        try:
            prior = float(cached)
            # Clamp to [0.05, 0.95] — prevent degenerate priors
            return max(0.05, min(0.95, prior))
        except (ValueError, TypeError):
            pass

    # Uninformative prior (Jeffreys prior for Bernoulli: Beta(0.5, 0.5))
    # We use 0.50 as the MAP estimate of Beta(0.5, 0.5).
    await log.adebug("prior_cache_miss", symbol=asset_symbol, desk_id=desk_id)
    return 0.50


# ---------------------------------------------------------------------------
# 3. Macro Context — Likelihood Ratio Adjustments
# ---------------------------------------------------------------------------

async def fetch_macro_context(redis_pool: aioredis.Redis) -> dict[str, Any]:
    """
    Fetch macro context from Redis cache (populated by Macro-MCP worker).

    In production, the Macro-MCP worker polls Alpha Vantage / LSEG for:
        - DXY (US Dollar Index) trend direction
        - 10Y Treasury Yield trend direction
        - VIX level and regime
        - Macro sentiment composite

    Cache key: oniquant:macro:latest
    TTL: 300s (refreshed every 5 minutes by the Macro-MCP worker)
    """
    cached = await redis_pool.get("oniquant:macro:latest")
    if cached is not None:
        try:
            return orjson.loads(cached)
        except orjson.JSONDecodeError:
            pass

    # Default: neutral macro environment (no adjustment)
    return {
        "dxy_trend": "neutral",       # "rising", "falling", "neutral"
        "yield_10y_trend": "neutral",  # "rising", "falling", "neutral"
        "vix_level": 18.0,
        "vix_regime": "normal",        # "low", "normal", "elevated", "crisis"
        "sentiment": "neutral",        # "risk_on", "neutral", "risk_off"
    }


# ---------------------------------------------------------------------------
# 4. Likelihood Computation — P(B|A) with Multiplier Stack
# ---------------------------------------------------------------------------

def compute_likelihood(
    signal: SignalInput,
    macro: dict[str, Any],
) -> tuple[float, str]:
    """
    Compute the adjusted Likelihood P(B|A) via multiplicative factors.

    The base likelihood starts at 1.0 (neutral) and is adjusted by
    three independent factors:

    ┌─────────────────────────────────────────────────────────────────┐
    │ Factor 1: IOF (Institutional Order Flow) Strength              │
    │   IOF > 0.80 → ×1.50 (strong institutional conviction)        │
    │   IOF > 0.60 → ×1.20 (moderate institutional flow)            │
    │   IOF < 0.30 → ×0.70 (weak/absent institutional backing)      │
    ├─────────────────────────────────────────────────────────────────┤
    │ Factor 2: Macro Alignment                                      │
    │   Signal direction aligns with macro regime → ×1.20            │
    │   Signal direction opposes macro regime → ×0.80                │
    │   Neutral macro → ×1.00 (no adjustment)                       │
    │                                                                │
    │   Alignment rules:                                             │
    │     LONG  Gold/Metals + DXY falling = aligned                  │
    │     SHORT Gold/Metals + DXY rising  = aligned                  │
    │     LONG  Equity + risk_on sentiment = aligned                 │
    │     SHORT Equity + risk_off sentiment = aligned                │
    │     LONG  Crypto + risk_on + low VIX = aligned                 │
    ├─────────────────────────────────────────────────────────────────┤
    │ Factor 3: Hurst Exponent Regime Weighting                      │
    │   H < 0.45 (mean-reverting) + Spline model → ×1.30            │
    │   H > 0.55 (trending) + kNN model → ×1.30                     │
    │   H matches model → ×1.15 (partial alignment)                 │
    │   H contradicts model → ×0.75                                  │
    │                                                                │
    │   Rationale: Hurst exponent measures long-range dependence.    │
    │   H < 0.5 → anti-persistent (mean-reverting): Spline Quantile │
    │     Regression excels because it models reversion boundaries.  │
    │   H > 0.5 → persistent (trending): kNN excels because it      │
    │     captures momentum continuation patterns.                   │
    └─────────────────────────────────────────────────────────────────┘

    Final likelihood is clamped to [LIKELIHOOD_FLOOR, LIKELIHOOD_CAP]
    to prevent numerically degenerate posteriors.

    Args:
        signal: The inbound signal with model metadata.
        macro: Macro context dict from fetch_macro_context().

    Returns:
        (likelihood, reasoning): The adjusted likelihood and a human-readable
        string documenting each multiplier applied.
    """
    likelihood = 1.0
    adjustments: list[str] = []

    # --- Factor 1: IOF Strength ---
    iof = signal.iof_strength
    if iof > 0.80:
        iof_mult = 1.50
        adjustments.append(f"IOF={iof:.2f}>0.80 → ×1.50")
    elif iof > 0.60:
        iof_mult = 1.20
        adjustments.append(f"IOF={iof:.2f}>0.60 → ×1.20")
    elif iof < 0.30:
        iof_mult = 0.70
        adjustments.append(f"IOF={iof:.2f}<0.30 → ×0.70")
    else:
        iof_mult = 1.00
        adjustments.append(f"IOF={iof:.2f} neutral → ×1.00")
    likelihood *= iof_mult

    # --- Factor 2: Macro Alignment ---
    dxy = macro.get("dxy_trend", "neutral")
    sentiment = macro.get("sentiment", "neutral")
    vix_regime = macro.get("vix_regime", "normal")
    asset_class = signal.asset_class.lower()
    direction = signal.direction  # 1=LONG, -1=SHORT

    macro_mult = 1.0
    macro_reason = "macro neutral"

    if asset_class in ("metals", "gold"):
        # Gold inverse-correlates with DXY
        if direction == 1 and dxy == "falling":
            macro_mult = 1.20
            macro_reason = "LONG metals + DXY falling → aligned ×1.20"
        elif direction == -1 and dxy == "rising":
            macro_mult = 1.20
            macro_reason = "SHORT metals + DXY rising → aligned ×1.20"
        elif direction == 1 and dxy == "rising":
            macro_mult = 0.80
            macro_reason = "LONG metals + DXY rising → opposed ×0.80"
        elif direction == -1 and dxy == "falling":
            macro_mult = 0.80
            macro_reason = "SHORT metals + DXY falling → opposed ×0.80"

    elif asset_class in ("equity", "index", "futures"):
        if direction == 1 and sentiment == "risk_on":
            macro_mult = 1.20
            macro_reason = "LONG equity + risk_on → aligned ×1.20"
        elif direction == -1 and sentiment == "risk_off":
            macro_mult = 1.20
            macro_reason = "SHORT equity + risk_off → aligned ×1.20"
        elif direction == 1 and sentiment == "risk_off":
            macro_mult = 0.80
            macro_reason = "LONG equity + risk_off → opposed ×0.80"
        elif direction == -1 and sentiment == "risk_on":
            macro_mult = 0.80
            macro_reason = "SHORT equity + risk_on → opposed ×0.80"

    elif asset_class in ("crypto", "perpetual", "spot_crypto"):
        if direction == 1 and sentiment == "risk_on" and vix_regime in ("low", "normal"):
            macro_mult = 1.20
            macro_reason = "LONG crypto + risk_on + low_VIX → aligned ×1.20"
        elif direction == -1 and sentiment == "risk_off":
            macro_mult = 1.20
            macro_reason = "SHORT crypto + risk_off → aligned ×1.20"
        elif direction == 1 and sentiment == "risk_off":
            macro_mult = 0.80
            macro_reason = "LONG crypto + risk_off → opposed ×0.80"

    likelihood *= macro_mult
    adjustments.append(macro_reason)

    # --- Factor 3: Hurst Exponent × Model Source ---
    H = signal.hurst_exponent
    model = signal.model_source.lower()

    if H < 0.45:
        # Mean-reverting regime
        if model == "spline":
            hurst_mult = 1.30
            hurst_reason = f"H={H:.3f}<0.45 (mean-revert) + Spline → ×1.30"
        elif model == "knn":
            hurst_mult = 0.75
            hurst_reason = f"H={H:.3f}<0.45 (mean-revert) + kNN → ×0.75 (mismatch)"
        else:
            hurst_mult = 1.00
            hurst_reason = f"H={H:.3f}<0.45 + {model} → ×1.00"
    elif H > 0.55:
        # Trending regime
        if model == "knn":
            hurst_mult = 1.30
            hurst_reason = f"H={H:.3f}>0.55 (trending) + kNN → ×1.30"
        elif model == "spline":
            hurst_mult = 0.75
            hurst_reason = f"H={H:.3f}>0.55 (trending) + Spline → ×0.75 (mismatch)"
        else:
            hurst_mult = 1.00
            hurst_reason = f"H={H:.3f}>0.55 + {model} → ×1.00"
    else:
        # Random walk regime (H ≈ 0.5) — no strong model preference
        hurst_mult = 1.00
        hurst_reason = f"H={H:.3f}≈0.50 (random walk) → ×1.00"

    likelihood *= hurst_mult
    adjustments.append(hurst_reason)

    # --- Clamp likelihood to prevent degenerate posteriors ---
    likelihood = max(LIKELIHOOD_FLOOR, min(LIKELIHOOD_CAP, likelihood))

    reasoning = " | ".join(adjustments)
    return likelihood, reasoning


# ---------------------------------------------------------------------------
# 5. Bayesian Posterior Calculation
# ---------------------------------------------------------------------------

def compute_posterior(
    prior: float,
    likelihood: float,
) -> float:
    """
    Compute Bayesian Posterior Probability P(A|B).

                    P(B|A) × P(A)
    P(A|B)  =  ─────────────────────
                       P(B)

    Where P(B) is the total evidence (marginal likelihood):

        P(B) = P(B|A)×P(A) + P(B|¬A)×P(¬A)

    We model P(B|¬A) as the complement adjustment:
        P(B|¬A) = 1 / likelihood    (inverse of the favorable likelihood)

    This ensures:
        - When likelihood > 1: P(B|A) > P(B|¬A), posterior > prior
        - When likelihood < 1: P(B|A) < P(B|¬A), posterior < prior
        - When likelihood = 1: posterior = prior (no update)

    This is equivalent to computing odds-form Bayes:
        posterior_odds = prior_odds × likelihood_ratio
        posterior = posterior_odds / (1 + posterior_odds)

    Args:
        prior: P(A) — historical win rate [0.05, 0.95].
        likelihood: P(B|A) — adjusted likelihood multiplier.

    Returns:
        Posterior probability P(A|B) ∈ (0, 1).
    """
    # Odds-form computation (numerically stable, avoids division by near-zero)
    #
    # prior_odds = P(A) / P(¬A) = P(A) / (1 - P(A))
    # posterior_odds = prior_odds × likelihood_ratio
    # P(A|B) = posterior_odds / (1 + posterior_odds)
    #
    # The likelihood_ratio here IS our computed likelihood, since we
    # defined it as P(B|A) / P(B|¬A) implicitly through the multiplier stack.

    prior_odds = prior / (1.0 - prior)
    posterior_odds = prior_odds * likelihood

    # Convert back to probability
    posterior = posterior_odds / (1.0 + posterior_odds)

    # Numerical safety clamp
    return max(0.0001, min(0.9999, posterior))


# ---------------------------------------------------------------------------
# 6. Routing Logic
# ---------------------------------------------------------------------------

def resolve_routing_target(asset_class: str) -> RoutingTarget | None:
    """
    Determine the execution broker based on asset class.

    TradFi (equity, forex, metals, futures, index) → IBKR_TWS
    Crypto (crypto, perpetual, spot_crypto)         → BYBIT_V5
    """
    return ROUTING_MAP.get(asset_class.lower())


# ---------------------------------------------------------------------------
# 7. Orchestrator — Main Decision Engine
# ---------------------------------------------------------------------------

class BayesianOrchestrator:
    """
    The CTO's decision engine. Evaluates every Alpha Stack signal
    through Bayesian inference and either authorizes or rejects it.

    Process per signal:
        1. Fetch Prior P(A) from TimescaleDB (via Redis cache).
        2. Fetch Macro Context from Macro-MCP (via Redis cache).
        3. Compute Likelihood P(B|A) with IOF, Macro, Hurst adjustments.
        4. Compute Posterior P(A|B) via odds-form Bayes.
        5. Decision: AUTHORIZE if posterior > 69.5%, else REJECT.
        6. Route authorized signals to the correct broker connector.
    """

    def __init__(self, redis_url: str = REDIS_URL) -> None:
        self._redis_url = redis_url
        self._pool: aioredis.Redis | None = None

        # Counters
        self._evaluated: int = 0
        self._authorized: int = 0
        self._rejected: int = 0

    async def connect(self) -> None:
        self._pool = aioredis.from_url(
            self._redis_url,
            decode_responses=False,
            max_connections=10,
            socket_connect_timeout=5.0,
            socket_keepalive=True,
        )
        await self._pool.ping()
        await log.ainfo("orchestrator_connected")

    async def disconnect(self) -> None:
        if self._pool:
            await self._pool.aclose()
        await log.ainfo(
            "orchestrator_disconnected",
            evaluated=self._evaluated,
            authorized=self._authorized,
            rejected=self._rejected,
            auth_rate=round(self._authorized / max(self._evaluated, 1), 4),
        )

    async def evaluate_signal(self, signal: SignalInput) -> OrchestratorOutput:
        """
        Full Bayesian evaluation pipeline for a single signal.

        Returns an OrchestratorOutput with AUTHORIZE or REJECT decision
        and complete mathematical reasoning trail.
        """
        t0 = time.perf_counter()

        # --- Step 1: Fetch Prior P(A) ---
        prior = await fetch_prior(
            asset_symbol=signal.asset_symbol,
            desk_id=signal.desk_id,
            redis_pool=self._pool,
        )

        # --- Step 2: Fetch Macro Context ---
        macro = await fetch_macro_context(self._pool)

        # --- Step 3: Compute Likelihood P(B|A) ---
        likelihood, likelihood_reasoning = compute_likelihood(signal, macro)

        # --- Step 4: Compute Posterior P(A|B) ---
        posterior = compute_posterior(prior, likelihood)

        # --- Step 5: Decision ---
        if posterior > POSTERIOR_FLOOR:
            decision = Decision.AUTHORIZE
            routing = resolve_routing_target(signal.asset_class)
            self._authorized += 1
        else:
            decision = Decision.REJECT
            routing = None
            self._rejected += 1

        self._evaluated += 1
        elapsed_us = (time.perf_counter() - t0) * 1_000_000

        # --- Build reasoning string ---
        reasoning = (
            f"P(A)={prior:.4f} [30d win rate] × "
            f"L={likelihood:.4f} [{likelihood_reasoning}] → "
            f"P(A|B)={posterior:.6f} "
            f"{'>' if posterior > POSTERIOR_FLOOR else '≤'} "
            f"{POSTERIOR_FLOOR} threshold"
        )

        output = OrchestratorOutput(
            signal_id=signal.signal_id,
            posterior_probability=posterior,
            decision=decision.value,
            routing_target=routing.value if routing else None,
            reasoning_math=reasoning,
        )

        # --- Step 6: Route authorized signals ---
        if decision == Decision.AUTHORIZE and self._pool is not None:
            await self._route_signal(signal, output)

        # --- Structured log ---
        await log.ainfo(
            "signal_evaluated",
            signal_id=signal.signal_id,
            symbol=signal.asset_symbol,
            model=signal.model_source,
            prior=round(prior, 4),
            likelihood=round(likelihood, 4),
            posterior=round(posterior, 6),
            decision=decision.value,
            routing=routing.value if routing else "DROPPED",
            latency_us=round(elapsed_us, 1),
        )

        return output

    async def _route_signal(
        self,
        signal: SignalInput,
        output: OrchestratorOutput,
    ) -> None:
        """
        Route an authorized signal to the appropriate broker connector.

        Pushes to the `oniquant:active_executions` Redis Stream with
        routing metadata so the execution layer knows which broker
        module to invoke.
        """
        execution_payload: dict[str, Any] = {
            "signal_id": signal.signal_id,
            "asset_symbol": signal.asset_symbol,
            "asset_class": signal.asset_class,
            "direction": signal.direction,
            "target_price": signal.target_price,
            "confidence": signal.confidence,
            "desk_id": signal.desk_id,
            "model_source": signal.model_source,
            "posterior_probability": output.posterior_probability,
            "routing_target": output.routing_target,
            "decision": output.decision,
            "reasoning_math": output.reasoning_math,
            "authorized_at": time.time(),
            "indicator_metadata": signal.indicator_metadata,
        }

        await self._pool.xadd(
            EXEC_STREAM,
            {
                "payload": orjson.dumps(execution_payload),
                "source": b"bayesian_orchestrator",
            },
            maxlen=EXEC_STREAM_MAXLEN,
            approximate=True,
        )

    # ------------------------------------------------------------------
    # Batch evaluation (for backtest / replay)
    # ------------------------------------------------------------------

    async def evaluate_batch(
        self,
        signals: list[SignalInput],
    ) -> list[OrchestratorOutput]:
        """
        Evaluate a batch of signals concurrently.

        Uses asyncio.gather for parallel Prior/Macro fetches across signals.
        """
        tasks = [self.evaluate_signal(s) for s in signals]
        return await asyncio.gather(*tasks)

    # ------------------------------------------------------------------
    # Statistics
    # ------------------------------------------------------------------

    @property
    def stats(self) -> dict[str, Any]:
        total = max(self._evaluated, 1)
        return {
            "evaluated": self._evaluated,
            "authorized": self._authorized,
            "rejected": self._rejected,
            "auth_rate": round(self._authorized / total, 4),
            "reject_rate": round(self._rejected / total, 4),
        }


# ---------------------------------------------------------------------------
# 8. Stream Consumer — Continuous Signal Processing Loop
# ---------------------------------------------------------------------------

async def run_orchestrator_consumer(
    redis_url: str = REDIS_URL,
    input_stream: str = "oniquant:raw_signals",
    consumer_group: str = "orchestrator_cg",
    consumer_name: str = "orchestrator_worker_0",
) -> None:
    """
    Consume signals from Redis Stream and run Bayesian evaluation.

    Uses XREADGROUP consumer group pattern for:
        - At-least-once delivery guarantee
        - Horizontal scaling (multiple consumer workers)
        - Automatic rebalancing on worker failure

    Flow:
        XREADGROUP oniquant:raw_signals → parse signal → evaluate → XACK
    """
    orchestrator = BayesianOrchestrator(redis_url=redis_url)
    await orchestrator.connect()

    pool = await orchestrator._pool

    # Ensure consumer group exists (idempotent)
    try:
        await pool.xgroup_create(input_stream, consumer_group, id="0", mkstream=True)
    except aioredis.ResponseError as e:
        if "BUSYGROUP" not in str(e):
            raise

    await log.ainfo(
        "orchestrator_consumer_started",
        stream=input_stream,
        group=consumer_group,
        consumer=consumer_name,
    )

    while True:
        try:
            # Block for up to 1 second waiting for new messages
            messages = await pool.xreadgroup(
                groupname=consumer_group,
                consumername=consumer_name,
                streams={input_stream: ">"},
                count=10,
                block=1000,
            )

            if not messages:
                continue

            for stream_name, entries in messages:
                for msg_id, msg_data in entries:
                    try:
                        raw_payload = msg_data.get(b"payload", b"{}")
                        payload = orjson.loads(raw_payload)

                        # Construct SignalInput from raw payload
                        signal = SignalInput(
                            signal_id=payload.get("signal_id", str(uuid.uuid4())),
                            asset_symbol=payload.get("asset_symbol", "UNKNOWN"),
                            asset_class=payload.get("asset_class", "equity"),
                            desk_id=payload.get("desk_id", "unknown"),
                            direction=payload.get("signal_direction", 1),
                            target_price=payload.get("target_price", 0.0),
                            confidence=payload.get("confidence", 0.5),
                            model_source=payload.get("model_source", "unknown"),
                            iof_strength=payload.get("iof_strength", 0.5),
                            hurst_exponent=payload.get("hurst_exponent", 0.5),
                            macro_context=payload.get("macro_context", {}),
                            indicator_metadata=payload.get("indicator_metadata", {}),
                        )

                        # Evaluate through Bayesian engine
                        result = await orchestrator.evaluate_signal(signal)

                        # ACK the message — successfully processed
                        await pool.xack(input_stream, consumer_group, msg_id)

                    except Exception as e:
                        await log.aerror(
                            "signal_processing_error",
                            msg_id=msg_id,
                            error=str(e),
                            error_type=type(e).__name__,
                        )
                        # Don't ACK — message will be re-delivered to another consumer

        except aioredis.ConnectionError as e:
            await log.aerror("orchestrator_redis_lost", error=str(e))
            await asyncio.sleep(2.0)
        except Exception as e:
            await log.aerror("orchestrator_loop_error", error=str(e))
            await asyncio.sleep(0.5)


# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import signal as os_signal

    async def main() -> None:
        loop = asyncio.get_running_loop()
        stop_event = asyncio.Event()

        for sig in (os_signal.SIGTERM, os_signal.SIGINT):
            loop.add_signal_handler(sig, stop_event.set)

        consumer_task = asyncio.create_task(run_orchestrator_consumer())

        await stop_event.wait()
        consumer_task.cancel()

    asyncio.run(main())
